version: '3.8'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.3.1
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./data/certs:/etc/nginx/certs:ro
      - ./data/vhost.d:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
      - ./data/dhparam:/etc/nginx/dhparam
    networks:
      - proxy-tier
    environment:
      - ENABLE_IPV6=false

  acme-companion:
    image: nginxproxy/acme-companion:2.6.0
    container_name: acme-companion
    restart: unless-stopped
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/certs:/etc/nginx/certs:rw
      - ./data/acme:/etc/acme.sh
      - ./data/vhost.d:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
      - ./data/dhparam:/etc/nginx/dhparam
    networks:
      - proxy-tier
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy

networks:
  proxy-tier:
    external: true