version: '3'
services:
  gateway:
    build: .
    container_name: gateway
    ports:
      - "443:443"
      - "80:80"
    networks:
      - gateway-network

networks:
  gateway-network:
    external: true