version: '3.8'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.3.1
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./data/certs:/etc/nginx/certs:ro
      - ./data/html:/usr/share/nginx/html:ro
    networks:
      - nginx-proxy

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: acme-companion
    restart: always
    depends_on:
      - nginx-proxy
    environment:
      - DEFAULT_EMAIL=savuliak.roman@gmail.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/certs:/etc/nginx/certs
      - ./data/html:/usr/share/nginx/html
      - ./data/acme:/etc/acme.sh
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true